apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app

    spec:
      containers:
      - name: ctn
        image: mechameleon/nginx-short-app
        ports:
        - containerPort: 8080