apiVersion: apps/v1
kind: Deployment
metadata:
  name: spirits-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: ctn
        image: php-nginx 
        imagePullPolicy: Never
        ports:
        - containerPort: 8080