apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
      - port: 3000
        targetPort: 3000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels: 
    app: adminer
spec:
  selector:
    app: adminer
  ports:
      - port: 8080
        targetPort: 8080
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: api
  labels: 
    app: api
spec:
  selector:
    app: api
  ports:
      - port: 5555
        targetPort: 5000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels: 
    app: mysql
spec:
  selector:
    app: mysql
  ports:
      - port: 3306
        targetPort: 3306
  type: LoadBalancer
