---
- name: Create EKS cluster
  command: >
    eksctl create cluster
    --name {{ cluster_name }}
    --region {{ region }}
    --nodegroup-name {{ nodegroup_name }}
  args:
    creates: /tmp/{{ cluster_name }}.cluster.created

- name: Wait for the EKS cluster to be ready
  command: >
    eksctl utils wait-nodes
    --cluster {{ cluster_name }}
    --region {{ region }}
  retries: 5
  delay: 60
  register: wait_output
  until: wait_output.rc == 0
